### ISSUE TITLE
Blocked by CORS Policy

### ISSUE THREAD

**Issue by edypaul** [MarketingPipeline/Pluto-TV.js#1]
Hello. I am working on an app that uses your Pluto-TV library, everything works fine using a local server. I deployed the app to different servers online and I'm getting this error in the console and the channels are not loading. 

![pluto-tv-error](https://user-images.githubusercontent.com/28904325/235337472-1e1e1b4c-e29f-47ee-baf1-ddb5006c8dd3.jpg)

Any idea on how to solve this issue?

**Comment by MarketingPip** [comment]
Hey @edypaul - 

Just seeing this now! Hope you are doing well! ✌️ 

To answer this question - this would mean the servers you are deploying this to are not located in a country that Pluto TV can be accessed from. Now to answer this how to fix this problem from a technical stand point - you could direct the traffic request through a server in a country that does have access to this content. Which you could do by changing the fetch request to a URL / server like example "https://your-cors-proxy-here.com/url?=link_to_pluto_here". 

But that might break copyright laws. 

Tho - I am not a lawyer, so I can not advise on that etc... Nor do I want to provide you with misinformation! So I would suggest consulting with a lawyer depending on whatever you are doing... Nor do I condone breaking any laws etc. 

Hope this answers your question! 

I will leave this open if you have any other questions I can help you with. 

ps; keep in mind - I would assume they check for copyright reasons where the request of location is sent from (server & client wise). Meaning - request of IP and origin server might need to be from a country that follows their copyright / streaming policies. Tho I can not answer that for sure.

**Comment by edypaul** [comment]
Thanks for answering.  I deployed the app to Netlify and Github pages just to test it. I don't want to break the law. I guess I'll just have to abandon the project.

**Comment by MarketingPip** [comment]
@edypaul - as said, not sure if it does break the law etc. 

But I don't want to give you a false information that does get / could get you in trouble/ does break the law! (Hence why I said - possibly advise a lawyer with some expertise etc..) - just my two cents tho! 

Hope this helped answer your question / issue & wish you luck on whatever you are doing! 👍

**Comment by edypaul** [comment]
Thank you !  Good luck to you too.
